// export const listData = [
//   {
//     id: 1,
//     title: "A Great Apartment Next to the Beach!",
//     images: "https://images.pexels.com/photos/1776574/pexels-photo-1776574.jpeg?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 2,
//     bathroom: 1,
//     price: 1000,
//     address: "Clifton, Karachi",
//     latitude: 24.8264,
//     longitude: 67.0338,
//   },
//   {
//     id: 2,
//     title: "Modern Apartment in the City Center",
//     images: "https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 3,
//     bathroom: 2,
//     price: 2000,
//     address: "Gulberg, Lahore",
//     latitude: 31.5204,
//     longitude: 74.3587,
//   },
//   {
//     id: 3,
//     title: "Cozy Cottage in the Countryside",
//     images: "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 4,
//     bathroom: 3,
//     price: 1500,
//     address: "Murree Road, Rawalpindi",
//     latitude: 33.6844,
//     longitude: 73.0479,
//   },
//   {
//     id: 4,
//     title: "Luxurious Villa with Private Pool",
//     images: "https://images.pexels.com/photos/1668860/pexels-photo-1668860.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//     bedroom: 5,
//     bathroom: 4,
//     price: 3000,
//     address: "DHA Phase 5, Karachi",
//     latitude: 24.8147,
//     longitude: 67.035,
//   },
//   {
//     id: 5,
//     title: "Spacious Family Home in Suburb",
//     images: "https://images.pexels.com/photos/7534283/pexels-photo-7534283.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
//     bedroom: 4,
//     bathroom: 2,
//     price: 1800,
//     address: "Bahria Town, Islamabad",
//     latitude: 33.5651,
//     longitude: 73.0169,
//   },
//   {
//     id: 6,
//     title: "Charming Bungalow by the Lake",
//     bedroom: 2,
//     images: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
//     bathroom: 1,
//     price: 1200,
//     address: "Lake View Park, Gilgit",
//     latitude: 35.9195,
//     longitude: 74.3125,
//   },
//   {
//     id: 7,
//     title: "Penthouse with Stunning City Views",
//     images: "https://images.pexels.com/photos/3288103/pexels-photo-3288103.png?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 3,
//     bathroom: 2,
//     price: 2500,
//     address: "Blue Area, Faisalabad",
//     latitude: 31.4504,
//     longitude: 73.135,
//   },
//   {
//     id: 8,
//     title: "Cozy Studio in Historic District",
//     images: "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 1,
//     bathroom: 1,
//     price: 900,
//     address: "Old City, Lahore",
//     latitude: 31.582,
//     longitude: 74.3294,
//   },
//   {
//     id: 9,
//     title: "Elegant Townhouse with Garden",
//     images: "https://images.pexels.com/photos/3288100/pexels-photo-3288100.png?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 3,
//     bathroom: 2,
//     price: 1600,
//     address: "Cantt, Sialkot",
//     latitude: 32.4927,
//     longitude: 74.5318,
//   },
//   {
//     id: 10,
//     title: "Contemporary Loft in Art District",
//     images: "https://images.pexels.com/photos/1571472/pexels-photo-1571472.jpeg?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 2,
//     bathroom: 1,
//     price: 1300,
//     address: "Gujranwala City Center",
//     latitude: 32.1877,
//     longitude: 74.1945,
//   },
//   {
//     id: 11,
//     title: "Stunning Apartment in Quetta",
//     images: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=600",
//     bedroom: 3,
//     bathroom: 2,
//     price: 2200,
//     address: "Model Town, Quetta",
//     latitude: 30.1798,
//     longitude: 66.975,
//   },
// ];
// export const singlePostData = {
//   id: 1,
//   title: "Beautiful Apartment",
//   price: 1200,
//   images: [
//     "https://images.pexels.com/photos/323775/pexels-photo-323775.jpeg?auto=compress&cs=tinysrgb&w=600",
//     "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=600",
//     "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=600",
//     "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=600",
//   ],
//   bedRooms: 2,
//   bathroom: 1,
//   size: 861,
//   latitude: 33.6844,
//   longitude: 73.0479,
//   city: "Islamabad",
//   address: "1234 Islamabad Street",
//   school: "250m away",
//   bus: "100m away",
//   restaurant: "50m away",
//   description:
//     "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
// };

// export const userData = {
//   id: 1,
//   name: "John Doe",
//   images: "https://images.pexels.com/photos/20094341/pexels-photo-20094341/free-photo-of-portrait-of-man-wearing-brown-cap.jpeg?auto=compress&cs=tinysrgb&w=600",
// };

// export default listData;

export const listData = [
  {
    id: 1,
    title: "A Great Apartment Next to the Beach!",
    images: [
      "https://images.pexels.com/photos/1776574/pexels-photo-1776574.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 2,
    bathroom: 1,
    price: 1000,
    address: "Clifton, Karachi",
    latitude: 24.8264,
    longitude: 67.0338,
  },
  {
    id: 2,
    title: "Modern Apartment in the City Center",
    images: [
      "https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 3,
    bathroom: 2,
    price: 2000,
    address: "Gulberg, Lahore",
    latitude: 31.5204,
    longitude: 74.3587,
  },
  {
    id: 3,
    title: "Cozy Cottage in the Countryside",
    images: [
      "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 4,
    bathroom: 3,
    price: 1500,
    address: "Murree Road, Rawalpindi",
    latitude: 33.6844,
    longitude: 73.0479,
  },
  {
    id: 4,
    title: "Luxurious Villa with Private Pool",
    images: [
      "https://images.pexels.com/photos/1668860/pexels-photo-1668860.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    bedroom: 5,
    bathroom: 4,
    price: 3000,
    address: "DHA Phase 5, Karachi",
    latitude: 24.8147,
    longitude: 67.035,
  },
  {
    id: 5,
    title: "Spacious Family Home in Suburb",
    images: [
      "https://images.pexels.com/photos/7534283/pexels-photo-7534283.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    ],
    bedroom: 4,
    bathroom: 2,
    price: 1800,
    address: "Bahria Town, Islamabad",
    latitude: 33.5651,
    longitude: 73.0169,
  },
  {
    id: 6,
    title: "Charming Bungalow by the Lake",
    images: [
      "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    bedroom: 2,
    bathroom: 1,
    price: 1200,
    address: "Lake View Park, Gilgit",
    latitude: 35.9195,
    longitude: 74.3125,
  },
  {
    id: 7,
    title: "Penthouse with Stunning City Views",
    images: [
      "https://images.pexels.com/photos/3288103/pexels-photo-3288103.png?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 3,
    bathroom: 2,
    price: 2500,
    address: "Blue Area, Faisalabad",
    latitude: 31.4504,
    longitude: 73.135,
  },
  {
    id: 8,
    title: "Cozy Studio in Historic District",
    images: [
      "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 1,
    bathroom: 1,
    price: 900,
    address: "Old City, Lahore",
    latitude: 31.582,
    longitude: 74.3294,
  },
  {
    id: 9,
    title: "Elegant Townhouse with Garden",
    images: [
      "https://images.pexels.com/photos/3288100/pexels-photo-3288100.png?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 3,
    bathroom: 2,
    price: 1600,
    address: "Cantt, Sialkot",
    latitude: 32.4927,
    longitude: 74.5318,
  },
  {
    id: 10,
    title: "Contemporary Loft in Art District",
    images: [
      "https://images.pexels.com/photos/1571472/pexels-photo-1571472.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 2,
    bathroom: 1,
    price: 1300,
    address: "Gujranwala City Center",
    latitude: 32.1877,
    longitude: 74.1945,
  },
  {
    id: 11,
    title: "Stunning Apartment in Quetta",
    images: [
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    bedroom: 3,
    bathroom: 2,
    price: 2200,
    address: "Model Town, Quetta",
    latitude: 30.1798,
    longitude: 66.975,
  },
];
export const singlePostData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 1200,
  images: [
    "https://images.pexels.com/photos/323775/pexels-photo-323775.jpeg?auto=compress&cs=tinysrgb&w=600",
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=600",
    "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=600",
    "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=600",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: 33.6844,
  longitude: 73.0479,
  city: "Islamabad",
  address: "1234 Islamabad Street",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
};

export const userData = {
  id: 1,
  name: "John Doe",
  images: [
    "https://images.pexels.com/photos/20094341/pexels-photo-20094341/free-photo-of-portrait-of-man-wearing-brown-cap.jpeg?auto=compress&cs=tinysrgb&w=600",
  ],
};

export default listData;
